require('util.key')
require('util.dequeue')

local mock = require("tests.mock")

local keypresses = Dequeue()

local function press(k)
  keypresses:push_front(k)
end

describe('mocker', function()
  mock.mock_love({})

  describe('mocks keystrokes', function()
    it('Ctrl-S', function()
      mock.keystroke('C-s', press, true)
      assert.is_true(Key.ctrl())
      assert.same('s', keypresses:pop_front())
      mock.release_keys()
    end)
    it('Alt-up', function()
      mock.keystroke('M-up', press, true)
      assert.is_true(Key.alt())
      assert.same('up', keypresses:pop_front())
      mock.release_keys()
    end)
    it('Shift-esc', function()
      mock.keystroke('S-esc', press, true)
      assert.is_true(Key.shift())
      assert.same('esc', keypresses:pop_front())
      mock.release_keys()
    end)
    it('Ctrl-Shift-Q', function()
      mock.keystroke('C-S-q', press, true)
      assert.is_true(Key.ctrl())
      assert.is_true(Key.shift())
      assert.same('q', keypresses:pop_front())
      mock.release_keys()
    end)
  end)
end)
